package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
  ENGLISH("en", "English", "🇬🇧"),
  SWAHILI("sw", "Kiswahili", "🇹🇿")
}

data class AppStrings(
  // Brand & General
  val appName: String,
  val firmName: String,
  val firmTagline: String,
  val cancel: String,
  val save: String,
  val submit: String,
  val back: String,
  val next: String,
  val done: String,
  val close: String,
  val retry: String,
  val search: String,
  val filter: String,
  val all: String,
  val viewDetails: String,
  val contactOffice: String,
  val loading: String,
  val error: String,
  val success: String,

  // Navigation
  val navHome: String,
  val navRequests: String,
  val navMatters: String,
  val navMessages: String,
  val navAppointments: String,
  val navDocuments: String,
  val navInvoices: String,
  val navNotifications: String,
  val navProfile: String,
  val navSettings: String,

  // Auth
  val welcomeTitle: String,
  val welcomeSubtitle: String,
  val signIn: String,
  val signUp: String,
  val email: String,
  val password: String,
  val confirmPassword: String,
  val fullName: String,
  val phoneNumber: String,
  val nationalId: String,
  val forgotPassword: String,
  val forgotPasswordPrompt: String,
  val resetPassword: String,
  val sendResetLink: String,
  val dontHaveAccount: String,
  val alreadyHaveAccount: String,
  val logout: String,
  val logoutConfirmation: String,
  val quickDemoLogin: String,

  // Home Dashboard
  val greeting: String,
  val clientWorkspace: String,
  val activeRequests: String,
  val activeMatters: String,
  val pendingInvoices: String,
  val upcomingConsultation: String,
  val unreadMessagesCount: String,
  val quickActions: String,
  val actionMakeRequest: String,
  val actionBookConsultation: String,
  val actionViewInvoices: String,
  val actionContactOffice: String,
  val recentActivity: String,
  val noUpcomingConsultations: String,

  // Requests
  val requestsTitle: String,
  val newRequest: String,
  val requestIntakeNotice: String,
  val requestNoticeDisclaimer: String,
  val stepClientInfo: String,
  val stepCategory: String,
  val stepDescription: String,
  val stepDocuments: String,
  val stepReview: String,
  val legalCategory: String,
  val urgencyLevel: String,
  val urgencyNormal: String,
  val urgencyUrgent: String,
  val urgencyCritical: String,
  val caseDescription: String,
  val caseDescriptionHint: String,
  val opposingParty: String,
  val desiredOutcome: String,
  val attachDocuments: String,
  val addDocument: String,
  val submissionSuccess: String,
  val submissionSuccessDetail: String,
  val viewRequestAction: String,
  val statusDraft: String,
  val statusSubmitted: String,
  val statusPaymentRequired: String,
  val statusPaymentPending: String,
  val statusPaymentSubmitted: String,
  val statusPaymentApproved: String,
  val statusAwaitingProcessing: String,
  val statusAccepted: String,
  val statusRejected: String,
  val paymentApprovedAwaitingProcessing: String,
  val emptyRequestsTitle: String,
  val emptyRequestsDesc: String,

  // Payment
  val paymentTitle: String,
  val invoiceReference: String,
  val amountDue: String,
  val paymentMethod: String,
  val lipaNumber: String,
  val qrCode: String,
  val bankAccount: String,
  val lipaInstructions: String,
  val qrInstructions: String,
  val bankInstructions: String,
  val uploadProof: String,
  val proofSubmitted: String,
  val underVerification: String,
  val paymentApprovedTitle: String,
  val paymentApprovedDesc: String,
  val paymentRejectedTitle: String,
  val paymentRejectedDesc: String,
  val repayNow: String,
  val simulateApproval: String,
  val simulateRejection: String,
  val referenceNumber: String,
  val transactionId: String,

  // Matters
  val mattersTitle: String,
  val matterReference: String,
  val leadAdvocate: String,
  val courtLocation: String,
  val milestoneProgress: String,
  val relatedRequest: String,
  val relatedDocuments: String,
  val relatedInvoices: String,
  val relatedAppointments: String,
  val emptyMattersTitle: String,
  val emptyMattersDesc: String,

  // Messages
  val messagesTitle: String,
  val messageOffice: String,
  val typeMessageHint: String,
  val send: String,
  val onlineStatus: String,
  val relatedMatterContext: String,
  val emptyMessagesTitle: String,
  val emptyMessagesDesc: String,

  // Appointments
  val appointmentsTitle: String,
  val bookConsultation: String,
  val selectAdvocate: String,
  val consultationType: String,
  val modeInPerson: String,
  val modeVirtual: String,
  val selectDate: String,
  val selectTime: String,
  val consultationNotes: String,
  val consultationFee: String,
  val confirmBooking: String,
  val emptyAppointmentsTitle: String,
  val emptyAppointmentsDesc: String,

  // Documents
  val documentsTitle: String,
  val uploadDocument: String,
  val documentCategory: String,
  val documentSize: String,
  val documentUploadedDate: String,
  val documentVerified: String,
  val emptyDocumentsTitle: String,
  val emptyDocumentsDesc: String,

  // Invoices
  val invoicesTitle: String,
  val invoiceNumber: String,
  val issueDate: String,
  val dueDate: String,
  val payNow: String,
  val statusUnpaid: String,
  val statusPaid: String,
  val emptyInvoicesTitle: String,
  val emptyInvoicesDesc: String,

  // Notifications
  val notificationsTitle: String,
  val markAllAsRead: String,
  val emptyNotificationsTitle: String,
  val emptyNotificationsDesc: String,

  // Profile & Settings
  val profileTitle: String,
  val personalInfo: String,
  val contactInfo: String,
  val settingsTitle: String,
  val darkMode: String,
  val lightMode: String,
  val language: String,
  val pushNotifications: String,
  val biometricLogin: String,
  val fontSize: String,
  val reducedMotion: String,
  val aboutFirm: String,
  val firmAddress: String,
  val firmPhone: String,
  val firmEmail: String
)

val EnglishTranslations = AppStrings(
  appName = "ET CETRA",
  firmName = "ET CETRA ADVOCATES COMPANY LIMITED",
  firmTagline = "Premier Legal Counsel & Corporate Advisory",
  cancel = "Cancel",
  save = "Save",
  submit = "Submit",
  back = "Back",
  next = "Next",
  done = "Done",
  close = "Close",
  retry = "Retry",
  search = "Search...",
  filter = "Filter",
  all = "All",
  viewDetails = "View Details",
  contactOffice = "Contact Office",
  loading = "Loading...",
  error = "An error occurred",
  success = "Success",

  navHome = "Home",
  navRequests = "Requests",
  navMatters = "Matters",
  navMessages = "Messages",
  navAppointments = "Appointments",
  navDocuments = "Documents",
  navInvoices = "Invoices",
  navNotifications = "Notifications",
  navProfile = "Profile",
  navSettings = "Settings",

  welcomeTitle = "Legal Excellence & Dedicated Advocacy",
  welcomeSubtitle = "Welcome to the official client portal of Et Cetra Advocates Company Limited.",
  signIn = "Sign In",
  signUp = "Create Account",
  email = "Email Address",
  password = "Password",
  confirmPassword = "Confirm Password",
  fullName = "Full Legal Name",
  phoneNumber = "Phone Number",
  nationalId = "National ID / Passport No.",
  forgotPassword = "Forgot Password?",
  forgotPasswordPrompt = "Enter your registered email to receive a secure password reset link.",
  resetPassword = "Reset Password",
  sendResetLink = "Send Reset Link",
  dontHaveAccount = "Don't have an account? Sign Up",
  alreadyHaveAccount = "Already have an account? Sign In",
  logout = "Sign Out",
  logoutConfirmation = "Are you sure you want to sign out of your client session?",
  quickDemoLogin = "Quick Demo Access",

  greeting = "Welcome back",
  clientWorkspace = "Client Legal Portal",
  activeRequests = "Legal Requests",
  activeMatters = "Active Matters",
  pendingInvoices = "Pending Invoices",
  upcomingConsultation = "Upcoming Consultation",
  unreadMessagesCount = "Unread Messages",
  quickActions = "Quick Actions",
  actionMakeRequest = "Make a Request",
  actionBookConsultation = "Book Consultation",
  actionViewInvoices = "View Invoices",
  actionContactOffice = "Contact Office",
  recentActivity = "Recent Matter & Request Activity",
  noUpcomingConsultations = "No upcoming consultations scheduled",

  requestsTitle = "Legal Requests",
  newRequest = "New Request",
  requestIntakeNotice = "Multi-Step Intake Process",
  requestNoticeDisclaimer = "The request will not be accepted as a Matter until the required payment has been completed and approved.",
  stepClientInfo = "Client Info",
  stepCategory = "Legal Area",
  stepDescription = "Details",
  stepDocuments = "Attachments",
  stepReview = "Review & Submit",
  legalCategory = "Legal Practice Category",
  urgencyLevel = "Urgency Level",
  urgencyNormal = "Standard (3-5 business days)",
  urgencyUrgent = "Urgent (Within 48 hours)",
  urgencyCritical = "Emergency / Imminent Court Deadline",
  caseDescription = "Matter Description & Facts",
  caseDescriptionHint = "Provide a comprehensive overview of the dispute or legal requirement...",
  opposingParty = "Opposing Party / Counterparty (if any)",
  desiredOutcome = "Desired Legal Objective or Remedy",
  attachDocuments = "Attach Supporting Documents",
  addDocument = "Add Document",
  submissionSuccess = "Request Submitted Successfully",
  submissionSuccessDetail = "Your intake request has been registered. Please note: The request will not be accepted as a Matter until the required payment has been completed and approved.",
  viewRequestAction = "View Request Details",
  statusDraft = "Draft",
  statusSubmitted = "Submitted",
  statusPaymentRequired = "Payment Required",
  statusPaymentPending = "Payment Pending",
  statusPaymentSubmitted = "Payment Submitted",
  statusPaymentApproved = "Payment Approved",
  statusAwaitingProcessing = "Awaiting Processing",
  statusAccepted = "Accepted as Matter",
  statusRejected = "Request Rejected",
  paymentApprovedAwaitingProcessing = "Payment Approved — Awaiting Office Processing",
  emptyRequestsTitle = "No Legal Requests",
  emptyRequestsDesc = "You have not submitted any legal requests yet. Tap below to start a new intake.",

  paymentTitle = "Legal Fee Payment",
  invoiceReference = "Reference / Invoice #",
  amountDue = "Amount Payable",
  paymentMethod = "Payment Channel",
  lipaNumber = "Lipa Number (Till/Paybill)",
  qrCode = "Official QR Code",
  bankAccount = "Direct Bank Wire",
  lipaInstructions = "Pay directly via mobile money using the official Et Cetra Lipa Till Number. Enter your reference as the Account.",
  qrInstructions = "Scan this authoritative Merchant QR Code using your banking or mobile money app for exact verification.",
  bankInstructions = "Transfer directly to Et Cetra Advocates Company Limited institutional account. Quote invoice reference.",
  uploadProof = "Upload Payment Proof",
  proofSubmitted = "Proof Submitted for Office Verification",
  underVerification = "Under Verification by Accounts Dept.",
  paymentApprovedTitle = "Payment Verified & Approved",
  paymentApprovedDesc = "Your payment has been successfully credited by Et Cetra Advocates Accounts Dept.",
  paymentRejectedTitle = "Payment Verification Unsuccessful",
  paymentRejectedDesc = "The accounts department could not verify the submitted proof. Please review details and submit new proof.",
  repayNow = "Repay / Re-submit Proof",
  simulateApproval = "Simulate Office Approval",
  simulateRejection = "Simulate Office Rejection",
  referenceNumber = "Payment Reference",
  transactionId = "Transaction ID / Reference",

  mattersTitle = "Active Matters",
  matterReference = "Matter Ref",
  leadAdvocate = "Lead Advocate",
  courtLocation = "Jurisdiction / Forum",
  milestoneProgress = "Case Timeline & Milestones",
  relatedRequest = "Originating Request",
  relatedDocuments = "Matter Case Files",
  relatedInvoices = "Associated Invoices",
  relatedAppointments = "Court & Meeting Schedule",
  emptyMattersTitle = "No Active Matters Yet",
  emptyMattersDesc = "Matters are created once a legal request is approved and payment is verified by the firm.",

  messagesTitle = "Office Communications",
  messageOffice = "Et Cetra Legal Team",
  typeMessageHint = "Type your message to the legal team...",
  send = "Send",
  onlineStatus = "Official Chambers Channel",
  relatedMatterContext = "Context: ",
  emptyMessagesTitle = "No Messages",
  emptyMessagesDesc = "All direct communications with your advocates will appear here.",

  appointmentsTitle = "Consultations & Hearings",
  bookConsultation = "Schedule Consultation",
  selectAdvocate = "Assigned Advocate",
  consultationType = "Consultation Type",
  modeInPerson = "Chambers (Physical Office)",
  modeVirtual = "Secure Video Conference",
  selectDate = "Select Preferred Date",
  selectTime = "Select Time Slot",
  consultationNotes = "Consultation Agenda / Brief",
  consultationFee = "Consultation Fee",
  confirmBooking = "Confirm & Proceed to Payment",
  emptyAppointmentsTitle = "No Scheduled Appointments",
  emptyAppointmentsDesc = "Book an advisory session with our advocates at your convenience.",

  documentsTitle = "Document Repository",
  uploadDocument = "Upload Document",
  documentCategory = "Category",
  documentSize = "File Size",
  documentUploadedDate = "Uploaded On",
  documentVerified = "Chambers Verified",
  emptyDocumentsTitle = "No Documents Filed",
  emptyDocumentsDesc = "Securely upload contracts, affidavits, evidence, and official records.",

  invoicesTitle = "Fee Notes & Invoices",
  invoiceNumber = "Invoice Number",
  issueDate = "Issue Date",
  dueDate = "Due Date",
  payNow = "Pay Invoice",
  statusUnpaid = "Unpaid",
  statusPaid = "Settled",
  emptyInvoicesTitle = "No Invoices Issued",
  emptyInvoicesDesc = "All fee notes, court disbursement bills, and retainer statements appear here.",

  notificationsTitle = "Chambers Notifications",
  markAllAsRead = "Mark all as read",
  emptyNotificationsTitle = "No Notifications",
  emptyNotificationsDesc = "You are fully up to date with all case filings, payments, and deadlines.",

  profileTitle = "Client Profile",
  personalInfo = "Personal Information",
  contactInfo = "Contact & Firm Info",
  settingsTitle = "Application Preferences",
  darkMode = "Dark Theme",
  lightMode = "Light Theme",
  language = "Language / Lugha",
  pushNotifications = "Urgent Case Alerts",
  biometricLogin = "Biometric Authentication",
  fontSize = "Font Scale",
  reducedMotion = "Reduced Motion",
  aboutFirm = "About Et Cetra Advocates Co. Ltd",
  firmAddress = "Et Cetra Chambers, 7th Floor, Posta House, Dar es Salaam, Tanzania",
  firmPhone = "+255 22 211 8899 / +255 754 000 111",
  firmEmail = "clientservices@etcetraadvocates.co.tz"
)

val SwahiliTranslations = AppStrings(
  appName = "ET CETRA",
  firmName = "ET CETRA ADVOCATES COMPANY LIMITED",
  firmTagline = "Ushauri Bora wa Kisheria na Utetezi",
  cancel = "Ghairi",
  save = "Hifadhi",
  submit = "Wasilisha",
  back = "Rudi",
  next = "Endelea",
  done = "Imekamilika",
  close = "Funga",
  retry = "Jaribu Tena",
  search = "Tafuta...",
  filter = "Chuja",
  all = "Yote",
  viewDetails = "Angalia Maelezo",
  contactOffice = "Wasiliana na Ofisi",
  loading = "Inapakia...",
  error = "Hitilafu imetokea",
  success = "Imefanikiwa",

  navHome = "Mwanzo",
  navRequests = "Maombi",
  navMatters = "Mashauri",
  navMessages = "Ujumbe",
  navAppointments = "Miadi",
  navDocuments = "Nyaraka",
  navInvoices = "Ankara",
  navNotifications = "Taarifa",
  navProfile = "Wasifu",
  navSettings = "Mipangilio",

  welcomeTitle = "Umahiri wa Kisheria na Utetezi Thabiti",
  welcomeSubtitle = "Karibu kwenye mfumo rasmi wa wateja wa Et Cetra Advocates Company Limited.",
  signIn = "Ingia",
  signUp = "Fungua Akaunti",
  email = "Barua Pepe",
  password = "Nenosiri",
  confirmPassword = "Thibitisha Nenosiri",
  fullName = "Jina Kamili la Kisheria",
  phoneNumber = "Nambari ya Simu",
  nationalId = "NIDA / Pasipoti",
  forgotPassword = "Umesahau Nenosiri?",
  forgotPasswordPrompt = "Weka barua pepe yako ili kupokea kiungo cha kurejesha nenosiri.",
  resetPassword = "Rejesha Nenosiri",
  sendResetLink = "Tuma Kiungo cha Kurejesha",
  dontHaveAccount = "Huna akaunti? Jisajili",
  alreadyHaveAccount = "Una akaunti tayari? Ingia",
  logout = "Ondoka Kwenye Mfumo",
  logoutConfirmation = "Je, una uhakika unataka kuondoka kwenye mfumo?",
  quickDemoLogin = "Kuingia kwa Majaribio (Demo)",

  greeting = "Karibu tena",
  clientWorkspace = "Mfumo wa Kisheria wa Mteja",
  activeRequests = "Maombi ya Kisheria",
  activeMatters = "Mashauri Yanayoendelea",
  pendingInvoices = "Ankara Zinazosubiri",
  upcomingConsultation = "Kipindi Kijacho cha Ushauri",
  unreadMessagesCount = "Ujumbe Mpya",
  quickActions = "Hatua za Haraka",
  actionMakeRequest = "Wasilisha Ombi",
  actionBookConsultation = "Weka Miadi",
  actionViewInvoices = "Angalia Ankara",
  actionContactOffice = "Wasiliana na Ofisi",
  recentActivity = "Mwenendo wa Mashauri na Maombi",
  noUpcomingConsultations = "Hakuna miadi iliyoratibiwa kwa sasa",

  requestsTitle = "Maombi ya Kisheria",
  newRequest = "Ombi Jipya",
  requestIntakeNotice = "Utaratibu wa Kupokea Ombi",
  requestNoticeDisclaimer = "Ombi hili halitakubaliwa kuwa Shauri rasmi hadi pale malipo yanayotakiwa yatakapokamilika na kuidhinishwa.",
  stepClientInfo = "Taarifa za Mteja",
  stepCategory = "Idara ya Sheria",
  stepDescription = "Maelezo",
  stepDocuments = "Vielelezo",
  stepReview = "Kagua na Wasilisha",
  legalCategory = "Kitengo cha Kisheria",
  urgencyLevel = "Kiwango cha Uharaka",
  urgencyNormal = "Kawaida (Siku 3-5 za kazi)",
  urgencyUrgent = "Dharura (Masaa 48)",
  urgencyCritical = "Dharura Kubwa / Tarehe ya Mahakama Iko Karibu",
  caseDescription = "Maelezo na Ukweli wa Shauri",
  caseDescriptionHint = "Eleza kwa kina mgogoro au mahitaji ya kisheria...",
  opposingParty = "Upande wa Pili / Mhusika Mwingine (kama yupo)",
  desiredOutcome = "Matokeo Yanayotarajiwa ya Kisheria",
  attachDocuments = "Ambatisha Nyaraka Zinazohusika",
  addDocument = "Ongeza Nyaraka",
  submissionSuccess = "Ombi Limewasilishwa Kikamilifu",
  submissionSuccessDetail = "Ombi lako limesajiliwa rasmi. Zingatia: Ombi halitafunguliwa kuwa Shauri hadi malipo yatakapoidhinishwa na ofisi.",
  viewRequestAction = "Angalia Maelezo ya Ombi",
  statusDraft = "Rasimu",
  statusSubmitted = "Limewasilishwa",
  statusPaymentRequired = "Malipo Yanahitajika",
  statusPaymentPending = "Malipo Yanasubiriwa",
  statusPaymentSubmitted = "Uthibitisho Umewasilishwa",
  statusPaymentApproved = "Malipo Yameidhinishwa",
  statusAwaitingProcessing = "Inasubiri Kushughulikiwa Ofisini",
  statusAccepted = "Limekubaliwa kama Shauri",
  statusRejected = "Ombi Limekataliwa",
  paymentApprovedAwaitingProcessing = "Malipo Yameidhinishwa — Inasubiri Kushughulikiwa Ofisini",
  emptyRequestsTitle = "Hakuna Maombi",
  emptyRequestsDesc = "Bado hujaweka ombi lolote la kisheria. Bofya hapa chini kuanzisha ombi jipya.",

  paymentTitle = "Malipo ya Ada ya Kisheria",
  invoiceReference = "Kumbukumbu / Namba ya Ankara",
  amountDue = "Kiasi Kinachotakiwa Kulipwa",
  paymentMethod = "Njia ya Malipo",
  lipaNumber = "Namba ya Lipa (Till / Paybill)",
  qrCode = "Msimbo wa QR Rasmi",
  bankAccount = "Akaunti ya Benki",
  lipaInstructions = "Lipa kupitia huduma za simu ukitumia namba rasmi ya Lipa ya Et Cetra Advocates. Weka kumbukumbu ya ankara.",
  qrInstructions = "Changanua msimbo huu wa QR kupitia programu yako ya benki au fedha za simu kwa uhakiki wa moja kwa moja.",
  bankInstructions = "Tuma moja kwa moja kwenye akaunti ya taasisi ya Et Cetra Advocates Company Limited.",
  uploadProof = "Wasilisha Uthibitisho wa Malipo",
  proofSubmitted = "Uthibitisho Umepokewa kwa Uhakiki",
  underVerification = "Inahakikiwa na Idara ya Uhasibu",
  paymentApprovedTitle = "Malipo Yamehakikiwa na Kuidhinishwa",
  paymentApprovedDesc = "Malipo yako yamethibitishwa na kuingizwa rasmi na idara ya uhasibu ya Et Cetra Advocates.",
  paymentRejectedTitle = "Uhakiki wa Malipo Haukufanikiwa",
  paymentRejectedDesc = "Idara ya uhasibu haikuweza kuhakiki ushahidi wa malipo uliotumwa. Tafadhali kagua na utume upya.",
  repayNow = "Lipa Tena / Tuma Ushahidi Mpya",
  simulateApproval = "Iga Idhini ya Ofisi (Simulate Approval)",
  simulateRejection = "Iga Kukataa kwa Ofisi (Simulate Rejection)",
  referenceNumber = "Kumbukumbu ya Malipo",
  transactionId = "Nambari ya Muamala",

  mattersTitle = "Mashauri Yanayoendelea",
  matterReference = "Namba ya Shauri",
  leadAdvocate = "Wakili Kiongozi",
  courtLocation = "Mahakama / Eneo la Shauri",
  milestoneProgress = "Hatua za Shauri",
  relatedRequest = "Ombi Lililoanzisha",
  relatedDocuments = "Mafaili ya Shauri",
  relatedInvoices = "Ankara Zinazohusika",
  relatedAppointments = "Ratiba ya Mahakama na Vikao",
  emptyMattersTitle = "Hakuna Shauri Linaloendelea",
  emptyMattersDesc = "Mashauri hufunguliwa rasmi pale ombi la mteja linapoidhinishwa na malipo kukamilika.",

  messagesTitle = "Mawasiliano na Mawakili",
  messageOffice = "Timu ya Wanasheria ya Et Cetra",
  typeMessageHint = "Andika ujumbe wako kwa wanasheria...",
  send = "Tuma",
  onlineStatus = "Kituo Rasmi cha Mawasiliano",
  relatedMatterContext = "Muktadha: ",
  emptyMessagesTitle = "Hakuna Ujumbe",
  emptyMessagesDesc = "Mawasiliano yote na wanasheria wako yataonekana hapa.",

  appointmentsTitle = "Ushauri na Vikao vya Kisheria",
  bookConsultation = "Weka Miadi ya Ushauri",
  selectAdvocate = "Wakili Aliyepangwa",
  consultationType = "Aina ya Ushauri",
  modeInPerson = "Ofisini (Ana kwa Ana)",
  modeVirtual = "Kikao cha Video cha Mtandaoni",
  selectDate = "Chagua Tarehe",
  selectTime = "Chagua Saa",
  consultationNotes = "Ajenda / Muhtasari wa Kikao",
  consultationFee = "Ada ya Ushauri",
  confirmBooking = "Thibitisha na Endelea Kwenye Malipo",
  emptyAppointmentsTitle = "Hakuna Miadi Iliyopangwa",
  emptyAppointmentsDesc = "Panga kikao cha ushauri na mawakili wetu kwa wakati unaokufaa.",

  documentsTitle = "Hifadhi ya Nyaraka",
  uploadDocument = "Pakia Nyaraka",
  documentCategory = "Aina ya Nyaraka",
  documentSize = "Ukubwa wa Faili",
  documentUploadedDate = "Tarehe ya Kupakiwa",
  documentVerified = "Imethibitishwa na Ofisi",
  emptyDocumentsTitle = "Hakuna Nyaraka Zilizopakiwa",
  emptyDocumentsDesc = "Pakia mikataba, hati za viapo, ushahidi na kumbukumbu rasmi kwa usalama.",

  invoicesTitle = "Ankara na Ada",
  invoiceNumber = "Namba ya Ankara",
  issueDate = "Tarehe ya Kutolewa",
  dueDate = "Tarehe ya Mwisho",
  payNow = "Lipa Ankara",
  statusUnpaid = "Haijalipwa",
  statusPaid = "Imelipwa",
  emptyInvoicesTitle = "Hakuna Ankara Zilizotolewa",
  emptyInvoicesDesc = "Taarifa zote za ada, gharama za mahakama na hati za malipo zitaonekana hapa.",

  notificationsTitle = "Taarifa za Ofisi",
  markAllAsRead = "Weka zote kuwa zimesomwa",
  emptyNotificationsTitle = "Hakuna Taarifa Mpya",
  emptyNotificationsDesc = "Uko sambamba na taarifa zote za mashauri, malipo na tarehe muhimu.",

  profileTitle = "Wasifu wa Mteja",
  personalInfo = "Taarifa Binafsi",
  contactInfo = "Mawasiliano na Ofisi",
  settingsTitle = "Mipangilio ya Programu",
  darkMode = "Muonekano wa Giza (Dark Theme)",
  lightMode = "Muonekano wa Mwanga (Light Theme)",
  language = "Lugha / Language",
  pushNotifications = "Taarifa za Dharura",
  biometricLogin = "Kuingia kwa Alama ya Kidole",
  fontSize = "Ukubwa wa Maandishi",
  reducedMotion = "Kupunguza Mihemko (Reduced Motion)",
  aboutFirm = "Kuhusu Et Cetra Advocates Co. Ltd",
  firmAddress = "Jengo la Et Cetra, Ghorofa ya 7, Mtaa wa Posta, Dar es Salaam, Tanzania",
  firmPhone = "+255 22 211 8899 / +255 754 000 111",
  firmEmail = "clientservices@etcetraadvocates.co.tz"
)

fun getAppStrings(language: AppLanguage): AppStrings = when (language) {
  AppLanguage.ENGLISH -> EnglishTranslations
  AppLanguage.SWAHILI -> SwahiliTranslations
}

val LocalAppStrings = staticCompositionLocalOf { EnglishTranslations }
